### ISSUE TITLE
Please move ColumbusManuputty to the correct location after renaming

### ISSUE THREAD

**Issue by philmcneely** [vmanuputty/V4Q#2]
Per the directions:
Save the file in YOUR V4Q repository and push it to GitHub.
It should be located in **V4Q/Class12/TestTools1_Prework**/JohnSmith.txt (or whatever your name is).

**Comment by vmanuputty** [comment]
Location changed to Class12/TestTools1_Prework/.  Please check for error and do You want me to remove the other files? Thank you
